### ISSUE TITLE
All Experiment Requests

### ISSUE THREAD

**Issue by csfuzz** [csfuzz/fuzzbench#2]
@Fuzzbench team: Thank you for your kind assistance with our experiments. We opened this standing issue to request each round of experiments. Each request for a new experiment includes the following statements:
* fuzzers: fuzzers used in the new experiment;
* benchmarks: benchmarks used in the new experiment;
The bash script [service/run-csfuzz-experiments.sh](https://github.com/csfuzz/fuzzbench/) will automatically update the CSFuzz git submodules, set the benchmarks and fuzzers, and start the experiments.

**Comment by csfuzz** [comment]
@jonathanmetzman 
We are ready for the first experiment round.

>benchmarks="openssl_server curl_curl_fuzzer_imap curl_curl_fuzzer_smb curl_curl_fuzzer_smtp gstreamer_gst-discoverer
 nghttp2_nghttp2_fuzzer h2o_h2o-fuzzer-http2 mbedtls_fuzz_dtlsserver curl_curl_fuzzer ntp_fuzz_ntpd_receive"
>fuzzers="libfuzzer csfuzz"
trails=20
max_total_time=86400

Thank you for your kind assistance.

**Comment by csfuzz** [comment]
@jonathanmetzman 
Is there anything else I need to prepare？

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman
> We are ready for the first experiment round.
> 
> > benchmarks="openssl_server curl_curl_fuzzer_imap curl_curl_fuzzer_smb curl_curl_fuzzer_smtp gstreamer_gst-discoverer
> > nghttp2_nghttp2_fuzzer h2o_h2o-fuzzer-http2 mbedtls_fuzz_dtlsserver curl_curl_fuzzer ntp_fuzz_ntpd_receive"
> > fuzzers="libfuzzer csfuzz"
> > trails=20
> > max_total_time=86400
> 
> Thank you for your kind assistance.

Sorry, I was offline when you sent this and I lost it in my queue.
I'll run this experiment ASAP.

**Comment by jonathanmetzman** [comment]
Done.
I made this experiment private, but I guess that isn't really needed right?

**Comment by csfuzz** [comment]
@jonathanmetzman 
How do I take the results?

**Comment by jonathanmetzman** [comment]
It's in gs://fuzzbench-marcel-reports/experimental/2021-03-31-csfuzz/

Other reports will appear
in gs://fuzzbench-marcel-reports/experimental/$EXPERIMENT_NAME

**Comment by csfuzz** [comment]
Thanks!

Can you add my account to this bucket? bajinsheng@gmail.com
It prompts AccessDeniedException that I don't have permission to access this bucket.

**Comment by jonathanmetzman** [comment]
Done. Should work now.

**Comment by csfuzz** [comment]
I have the permission to access the folder, but still do not have the permission to access the files.

**Comment by jonathanmetzman** [comment]
Sorry, try again please.

**Comment by csfuzz** [comment]
Hi, we are ready for second experiment round. @jonathanmetzman 
This time we add a new fuzzer: "ifcg". 
>benchmarks="openssl_server curl_curl_fuzzer_imap curl_curl_fuzzer_smb curl_curl_fuzzer_smtp gstreamer_gst-discoverer
>nghttp2_nghttp2_fuzzer h2o_h2o-fuzzer-http2 mbedtls_fuzz_dtlsserver curl_curl_fuzzer ntp_fuzz_ntpd_receive"
>fuzzers="libfuzzer csfuzz ifcg"
>trails=20
>max_total_time=86400

The corresponding script  [service/run-csfuzz-experiments.sh](https://github.com/csfuzz/fuzzbench/blob/master/service/run-csfuzz-experiments.sh) has been updated.

Thanks!

**Comment by jonathanmetzman** [comment]
Done.

**Comment by csfuzz** [comment]
> Done.

Hi. The results look a bit wired. All targets exit around 8 hours. 
Can I check the output log of each trail?

**Comment by jonathanmetzman** [comment]
There's a missing comment about the results looking weird.
I suspect that's because there's a bottleneck in measuring (known problem in fuzzbench).
It will probably fix itself as more stuff gets measured.
You can view fuzzer logs in gs://fuzzbench-marcel-data/2021-04-08-csfuzz/experiment-folders/

**Comment by csfuzz** [comment]
Hi @jonathanmetzman Can I request to run these again?
>benchmarks="curl_curl_fuzzer_imap nghttp2_nghttp2_fuzzer mbedtls_fuzz_dtlsserver"
>fuzzers="libfuzzer csfuzz"
>trails=20
>max_total_time=86400
